### ISSUE TITLE
"High-Class Bitches"

### ISSUE THREAD

**Issue by optikfluffel** [icons8/flat-color-icons#3]
Hi, I really like your icons but what about that [High-Class Bitches](https://github.com/icons8/flat-color-icons/blame/master/README.md#L3-L5) nonsense?
Also [the License](http://icons8.com/good-boy-license/) excludes at least girls and lone fathers and I'm sure a bunch of other people too.

**Comment by visualpharm** [comment]
Obviously, we failed to make you laugh. Would you like us to make funnier jokes or to keep it serious?

**Comment by vkeusebio** [comment]
Make it less aggressive towards females

**Comment by optikfluffel** [comment]
@visualpharm I don't mind making jokes and taking things a little less serious, but the fun stops if you start hurting peoples feelings..

@vkeusebio :+1:

**Comment by visualpharm** [comment]
I see your point. I was the author of these jokes and obviously they failed.

Here's the story. Jokes should have a target; it's not funny otherwise. The thing is to choose a target so don't hurt anyone. I choose myself as a target often, it's a safe bet. Like for examply here we joke about my drawing skills: http://icons8.com/about — and for some time I was thinking about a carreer of an artist. 

For the bitches, I thought it's a pretty safe bet as no one would consider himself as a spoiled girl taking advantage of men. It was supported to be a fictional character, a cliche, not a live person: https://www.youtube.com/watch?v=iEe_eraFWWs

Obviously, it didn't work out; sorry about it! 

Btw, here's my draft with other beginnings: https://www.evernote.com/l/AA8n4GcVzJBIrYOyMiU6zieQnnl_tmaJIgk

**Comment by visualpharm** [comment]
I think I know what you mean by the license excluding the lone fathers; it's my personal situation too. 

I never thought about the [Good Boy License](http://icons8.com/good-boy-license/) this way; I took it as an idiom for "good things". Thanks for making me think!

**Comment by optikfluffel** [comment]
@visualpharm Thanks for caring :)

I really like Alternative 1:
> Honey,
>
> We’ve been together for a while, right? I love you, you love me, so let’s talk about our future :-) Here it is: [Ultimate Toolkit for Responsive Icons](http://icons8.com/responsive-icons).

**Comment by sebastienbarre** [comment]
This is a great-looking set of icons, but we had the same problem with your license here at work when one of our developer pointed it out. Some back & forth went, somewhat heated, and we ultimately had our lawyer chime in for advice. I'm not in a position to tell you what's fun or offensive, but would you consider dual licensing your work? Keep the Good Boy License for fun, and allow other parties to use the Creative Commons License as well, say [CC0](https://creativecommons.org/choose/zero/)? Thank you.

**Comment by visualpharm** [comment]
Well, that makes sense to us. Corporate lawyers may use something more serious. 

Maybe we should distribute it under MIT license as well. However, we don't know much about it. How can we do that without making it boring? Adding the reference to MIT to our license sounds like the opposite of fun.

**Comment by sebastienbarre** [comment]
@visualpharm thanks for the quick reply. I work with our lawyer regularly, and she has a good sense of humor. At the end of the day though, a license *is* a legal instrument, so a lawyer would be the one to shed some light on whether or not it is too ambiguous or vague to be enforced as such. @optikfluffel pointed out some issues already, and our lawyer also found out that there is some confusion over what the legal “mom” of our company would be. 

The point being, I certainly understand you would want to make it fun, but a license is a legal agreement at its core. You could call it "the Good Boy Mantra", or "the Good Boy Way of Life", i.e. allow people to use your work, provided that they do their best to abide to these terms. If you use the word "license" though, there is an assumption about enforcement, and as such I bet it will be scrutinized by lawyers.

As an anecdote, the [JSON license](http://www.json.org/license.html), which includes "```The Software shall be used for Good, not Evil```", was tongue-in-cheek back in the days, but has been considered harmful by many since then (see [here](http://tanguy.ortolo.eu/blog/article46/json-license), [here](http://www.avvo.com/legal-answers/does-a--do-no-evil--clause-have-legal-power--521902.html), and [here](https://www.gnu.org/philosophy/license-list.html#JSON)), even in the context of open-source or free software -- a generally well-intentioned community.

Dual-licensing would solve that issue. Here is an example on [Stack Overflow](http://stackoverflow.com/a/6787211/250457):
```
/*
 *   This library is dual-licensed: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License version <N> as 
 *   published by the Free Software Foundation. For the terms of this 
 *   license, see licenses/gpl_v<N>.txt or <http://www.gnu.org/licenses/>.
 *
 *   You are free to use this library under the terms of the GNU General
 *   Public License, but WITHOUT ANY WARRANTY; without even the implied 
 *   warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *   See the GNU General Public License for more details.
 *
 *  Alternatively, you can license this library under a commercial
 *  license, as set out in licenses/commercial.txt.
 */
```
and opinions about it [here](http://oss-watch.ac.uk/resources/duallicence2), and [here](http://p2pfoundation.net/Dual_Licensing).

Thank you

**Comment by Calinou** [comment]
:+1:. I would recommend [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by visualpharm** [comment]
Thank you for the great explanation.  

That makes sense to me. Let's distribute this icon pack under the standard MIT license. I'll make the corrections to the license page.   

By the way, I'd like your opinion on our [Linkware license](https://icons8.com/license/) for the rest of the library (we're releasing 1,200 icons soon). Our clients with lawyers buy a pay license, and we lack feedback.

**Comment by sebastienbarre** [comment]
Thanks @visualpharm (the [package.json](https://github.com/icons8/flat-color-icons/blob/master/package.json)'s `license` key might need an update too). 
As far as the other license is concerned, CC BY-ND 3.0 or "buy a license" seems pretty straightforward to me.

**Comment by visualpharm** [comment]
Thank you! 

You're right, we have to update package.json too. Will do.

**Comment by sebastienbarre** [comment]
Hey guys. Any update?

**Comment by visualpharm** [comment]
Hi Sebastien, I'm not sure what are you talking about. If you're talking about updating package.json, I have updated it same day. 

If you're about more icons, we have them here: https://icons8.com/color-icons. They have 2100 icons at the moment and are distributed for a fee, but these 312 ones are free forever under MIT.

**Comment by sebastienbarre** [comment]
Yes, the `package.json` had been updated, but the `LICENSE.md` and `README.md` had not, and my gut feeling is that these two would be considered more "authoritative". I see you just updated them as well earlier today, so that should do the trick. Thanks.

**Comment by visualpharm** [comment]
Right, I've started looking where we should update it and found these two. Thanks for the keeping track of things here!
